# https://docs.github.com/pt/actions/get-started/quickstart
name: Shell Linter
run-name: Shell-Linter By ShellChecker
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: Azbagheri/shell-linter@latest
        with:
          path: "*.sh"
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
